spring.application.name=orderbookings

server.port=8080

# Data file used by text-file repository.
booking.file.path=src/main/resources/data/bookings.txt

spring.thymeleaf.cache=false

# Multipart File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
